build:
  maxIssues: 0

config:
  validation: true

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true

style:
  MagicNumber:
    active: false

orion:
  NoRecursion:
    active: true
