on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Jitpack build
        uses: kylecorry31/jitpack-build@1.0.0
        with:
          version: ${{ github.event.release.tag_name }}
